"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navBar/Navbar";


import { Provider } from "react-redux";
import { store } from '@/store/store';
import { useEffect } from 'react';
import { useDispatch } from "react-redux";
import { onAuthStateChangedListener, createUserDocumentFromAuth } from '@/utils/firebase/firebase.utils';
import { setCurrentUser } from "@/store/user/user.action";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Men's Clothing PopUp",
//   description: "Generated by create next app",
// };

function AuthListener() {
  const dispatch = useDispatch();
  
  useEffect(() => {
    console.log('AuthListener useEffect running - setting up auth listener');
    
    const unsubscribe = onAuthStateChangedListener((user) => {
        console.log('Auth state changed:', user);
        if(user){
            console.log('User found, creating document');
            createUserDocumentFromAuth(user);
        }
        console.log('Dispatching setCurrentUser:', user);
        dispatch(setCurrentUser(user));
    });
    
    console.log('Auth listener set up, returning unsubscribe function');
    return unsubscribe;
  }, [dispatch])

  return null;
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider store={store}>
          <AuthListener />
         
            <Navbar />
            {children}
         
        </Provider>
      </body>
    </html>
  );
}
