"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Elements } from "@stripe/react-stripe-js";

import Navbar from "../components/navBar/Navbar";


import { Provider } from "react-redux";
import { store, persistor } from '@/store/store';
import { useEffect } from 'react';
import { useDispatch } from "react-redux";

import { checkUserSession, setCurrentUser } from "@/store/user/user.action";
import { PersistGate } from 'redux-persist/integration/react';
import { stripePromise } from "@/utils/stripe/stripe.utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Men's Clothing PopUp",
//   description: "Generated by create next app",
// };

function AuthListener() {
  const dispatch = useDispatch();
  
  useEffect(() => {
    dispatch(checkUserSession());
  }, [dispatch])

  return null;
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Men's Clothing Shop</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
          <AuthListener />
            <Navbar />
            <Elements stripe={stripePromise}>
            {children}
            </Elements>
            </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
