export const CART_ACTION_TYPES = {
    SET_CART_OPEN: 'cart/SET_CART_OPEN',
    ADD_ITEM_TO_CART: 'cart/ADD_ITEM_TO_CART',
    UPDATE_ITEM_QUANTITY: 'cart/UPDATE_ITEM_QUANTITY',
    REMOVE_ITEM_FROM_CART: 'cart/REMOVE_ITEM_FROM_CART',
    CLEAR_CART: 'cart/CLEAR_CART',

}